name: Keep Streamlit App Awake

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Wake app
        run: |
          wget -q -O /dev/null https://kapabravo-calorie-calculator.streamlit.app || true
